-- AUTO-GENERATED seed data for NEXA. Run AFTER schema.sql.
-- Idempotent: re-running upserts the same catalog rows.

insert into public.opportunities
  (id,title,organization,type,description,location,remote,categories,goals,career_stages,skills,funding,deadline,eligibility,benefits,application_url,source,verified) values
  ('ai-research-fellowship','AI Research Fellowship','Demo Research Foundation','Fellowship','A funded fellowship for early-career researchers working on applied AI/ML problems, with placement at partner labs abroad.','International',false,array['AI & Technology','Research']::text[],array['Study abroad','Get a scholarship','Build my skills']::text[],array['Student','Early career']::text[],array['AI/ML','Python','Research']::text[],'{"type":"Fully funded","amount":"Tuition + stipend"}'::jsonb,'2026-09-14'::date,array['Enrolled in or recently graduated from a STEM program','Demonstrated research interest in AI/ML','Open to international relocation']::text[],array['Full tuition and stipend','Mentorship from senior researchers','Publication support']::text[],'#','Demo',true),
  ('women-in-ai-scholarship','Women in AI Scholarship','Global AI Trust','Scholarship','Scholarship supporting women pursuing graduate study in artificial intelligence or machine learning.','International',false,array['AI & Technology','Women in Tech']::text[],array['Get a scholarship','Study abroad']::text[],array['Student']::text[],array['AI/ML','Data Science']::text[],'{"type":"Fully funded","amount":"Full tuition"}'::jsonb,'2026-09-21'::date,array['Identifies as a woman','Admitted to or enrolled in a graduate AI/ML program','Strong academic record']::text[],array['Full tuition coverage','Community of past scholars','Annual summit invitation']::text[],'#','Demo',true),
  ('global-research-fellowship','Global Research Fellowship','Meridian Foundation','Fellowship','Funding and placement for early-stage researchers across social science, health, and technology fields.','International',false,array['Research','Social Impact']::text[],array['Find funding','Study abroad']::text[],array['Student','Career changer']::text[],array['Research','Writing']::text[],'{"type":"Fully funded","amount":"$18,000 + travel"}'::jsonb,'2026-09-30'::date,array['Bachelor''s degree or equivalent experience','Research proposal required','No age restriction']::text[],array['Full funding','Institutional affiliation','Publication mentorship']::text[],'#','Demo',true),
  ('future-leaders-program','Future Leaders Program','Confluence Institute','Leadership','A year-long leadership development program for professionals moving into senior roles.','Remote',true,array['Leadership','Business']::text[],array['Grow my network','Change careers']::text[],array['Working professional','Career changer']::text[],array['Leadership','Communication']::text[],'{"type":"Paid","amount":"Stipend on completion"}'::jsonb,'2026-10-05'::date,array['3+ years of professional experience','Manager-track or aspiring to be','Available for monthly virtual sessions']::text[],array['1:1 executive coaching','Peer cohort','Certificate of completion']::text[],'#','Demo',true),
  ('tech-returnship','Tech Returnship Program','NorthPeak Systems','Returnship','A structured 16-week paid returnship for professionals re-entering the tech workforce after a career break.','Remote',true,array['AI & Technology','Business']::text[],array['Return to work','Build my skills']::text[],array['Returning to work']::text[],array['JavaScript','Communication']::text[],'{"type":"Paid","amount":"Market-rate salary"}'::jsonb,'2026-10-20'::date,array['Career break of 1+ years','Prior professional experience in tech or adjacent field','Based in or willing to work remote hours overlapping IST']::text[],array['Paid 16-week program','Mentorship','Potential full-time conversion']::text[],'#','Demo',true),
  ('women-founders-grant','Women Founders Micro-Grant','Catalyst Collective','Grant','Non-dilutive micro-grants for early-stage founders building their first company.','International',true,array['Entrepreneurship','Finance','Women in Tech']::text[],array['Start a business','Find funding']::text[],array['Entrepreneur']::text[],array['Finance','Leadership']::text[],'{"type":"Fully funded","amount":"$5,000 grant"}'::jsonb,'2026-11-12'::date,array['Founding team is majority women-led','Company under 2 years old','Not yet raised institutional funding']::text[],array['$5,000 non-dilutive grant','Founder community access','Office hours with mentors']::text[],'#','Demo',true),
  ('design-product-internship','Design & Product Bridge Internship','Studio Norr','Internship','A 10-week paid internship pairing design and product thinking, for early-career candidates building a portfolio.','Remote',true,array['Design & Creativity','Business']::text[],array['Find an internship','Build my skills']::text[],array['Student','Early career']::text[],array['UI/UX','Communication']::text[],'{"type":"Paid","amount":"$1,800/month"}'::jsonb,'2026-12-01'::date,array['Portfolio of design work (student or personal projects accepted)','Available for 10 consecutive weeks','No prior professional experience required']::text[],array['Paid stipend','Portfolio review','Mentor pairing']::text[],'#','Demo',true),
  ('healthtech-accelerator','HealthTech Founders Accelerator','Ridgeline Ventures','Incubator','12-week accelerator for early-stage health technology startups, with a small equity investment.','International',false,array['Healthcare','Entrepreneurship']::text[],array['Start a business','Grow my network']::text[],array['Entrepreneur']::text[],array['Research','Leadership']::text[],'{"type":"Partially funded","amount":"$25,000 for 5% equity"}'::jsonb,'2026-09-05'::date,array['Working prototype or MVP','Founding team of 1-4 people','Health/medtech focus']::text[],array['Seed investment','Clinical advisor network','Demo day']::text[],'#','Demo',true),
  ('public-policy-fellowship','Public Policy Fellowship','Anthemis Policy Lab','Fellowship','A 6-month fellowship for people transitioning into public policy and social impact careers.','Remote',true,array['Social Impact','Law']::text[],array['Change careers','Build my skills']::text[],array['Career changer','Between opportunities']::text[],array['Research','Writing','Public Speaking']::text[],'{"type":"Paid","amount":"$2,200/month"}'::jsonb,'2026-08-25'::date,array['Bachelor''s degree in any field','Interest in public policy or governance','Strong written communication']::text[],array['Paid stipend','Policy-writing workshops','Alumni network']::text[],'#','Demo',true),
  ('stem-mentorship-circle','STEM Mentorship Circle','Global STEM Network','Mentorship','A structured 4-month mentorship program pairing women in STEM with senior mentors in their field.','Remote',true,array['AI & Technology','Research','Women in Tech']::text[],array['Find mentors','Grow my network']::text[],array['Student','Early career','Career changer']::text[],array['Communication','Leadership']::text[],'{"type":"No funding","amount":null}'::jsonb,'2026-09-10'::date,array['Identifies as a woman in a STEM field','Available for monthly 1:1 sessions','No cost to apply']::text[],array['1:1 mentorship','Peer cohort events','Career workshops']::text[],'#','Demo',true),
  ('founders-pitch-competition','Emerging Founders Pitch Competition','Catalyst Collective','Competition','A pitch competition for early-stage founders with cash prizes and investor introductions.','International',false,array['Entrepreneurship','Business']::text[],array['Start a business','Find funding']::text[],array['Entrepreneur','Working professional']::text[],array['Public Speaking','Finance']::text[],'{"type":"Fully funded","amount":"$10,000 top prize"}'::jsonb,'2026-10-30'::date,array['Company under 3 years old','Under $500K raised to date','10-minute pitch deck required']::text[],array['Cash prizes','Investor introductions','Media coverage']::text[],'#','Demo',true),
  ('early-career-data-fellowship','Early-Career Data Science Fellowship','Meridian Foundation','Fellowship','A paid fellowship placing early-career candidates in data science roles at partner nonprofits.','Remote',true,array['AI & Technology','Social Impact']::text[],array['Get my first job','Build my skills']::text[],array['Student','Early career']::text[],array['Python','Data Science']::text[],'{"type":"Paid","amount":"$3,000/month"}'::jsonb,'2026-09-18'::date,array['Coursework or self-study in data science','Portfolio project preferred','Available full-time for 6 months']::text[],array['Paid placement','Nonprofit partner network','Skills certification']::text[],'#','Demo',true),
  ('creative-leadership-grant','Creative Leadership Grant','Studio Norr','Grant','Grant funding for designers and creatives moving into creative-direction and leadership roles.','Remote',true,array['Design & Creativity','Leadership']::text[],array['Grow my network','Build my skills']::text[],array['Working professional']::text[],array['UI/UX','Leadership']::text[],'{"type":"Partially funded","amount":"$4,000"}'::jsonb,'2026-11-25'::date,array['3+ years in a design discipline','Portfolio required','Based anywhere, remote-friendly']::text[],array['Grant funding','Leadership coaching','Studio community access']::text[],'#','Demo',true),
  ('return-to-finance-program','Return to Finance Program','NorthPeak Systems','Returnship','A returnship for finance professionals re-entering the workforce, with flexible part-time options.','India',false,array['Finance','Business']::text[],array['Return to work','Grow my network']::text[],array['Returning to work']::text[],array['Finance','Communication']::text[],'{"type":"Paid","amount":"Market-rate, pro-rated"}'::jsonb,'2026-12-15'::date,array['Career break of 1+ years','Prior finance or accounting experience','Based in India, hybrid role']::text[],array['Flexible hours','Paid role','Return-to-work coaching']::text[],'#','Demo',true),
  ('education-innovation-fellowship','Education Innovation Fellowship','Anthemis Policy Lab','Fellowship','A fellowship for educators and technologists building new approaches to learning.','International',false,array['Education','Social Impact']::text[],array['Change careers','Grow my network']::text[],array['Career changer','Working professional']::text[],array['Research','Communication']::text[],'{"type":"Fully funded","amount":"Stipend + travel"}'::jsonb,'2027-01-15'::date,array['Experience in education, ed-tech, or related field','Proposal required','Open to relocation for the fellowship term']::text[],array['Full funding','Global cohort','Publication opportunity']::text[],'#','Demo',true),
  ('media-storytelling-lab','Media & Storytelling Lab','Global STEM Network','Incubator','An 8-week lab for early-career media makers developing an independent storytelling project.','Remote',true,array['Media','Design & Creativity']::text[],array['Build my skills','Find an internship']::text[],array['Student','Early career']::text[],array['Writing','Communication']::text[],'{"type":"Unpaid","amount":null}'::jsonb,'2027-02-10'::date,array['A project concept or draft required','No professional experience required','Available for weekly virtual workshops']::text[],array['Mentor feedback','Peer showcase','Distribution support']::text[],'#','Demo',true),
  ('law-access-scholarship','Access to Law Scholarship','Anthemis Policy Lab','Scholarship','A scholarship supporting first-generation students pursuing legal education.','International',false,array['Law','Social Impact']::text[],array['Get a scholarship','Change careers']::text[],array['Student','Career changer']::text[],array['Research','Writing']::text[],'{"type":"Fully funded","amount":"Full tuition"}'::jsonb,'2026-08-18'::date,array['First-generation college student','Admitted to an accredited law program','Financial need demonstrated']::text[],array['Full tuition','Bar exam prep stipend','Mentor network']::text[],'#','Demo',true),
  ('archived-summer-fellowship','Summer Research Fellowship (Closed)','Demo Research Foundation','Fellowship','A past cohort''s summer fellowship — kept visible as a closed listing so deadline states are testable end to end.','International',false,array['Research','AI & Technology']::text[],array['Study abroad','Build my skills']::text[],array['Student']::text[],array['Research']::text[],'{"type":"Fully funded","amount":"Stipend"}'::jsonb,'2026-07-01'::date,array['This cohort has closed']::text[],array['N/A — applications closed']::text[],'#','Demo',true)
on conflict (id) do update set
  title=excluded.title, organization=excluded.organization, type=excluded.type, description=excluded.description,
  location=excluded.location, remote=excluded.remote, categories=excluded.categories, goals=excluded.goals,
  career_stages=excluded.career_stages, skills=excluded.skills, funding=excluded.funding, deadline=excluded.deadline,
  eligibility=excluded.eligibility, benefits=excluded.benefits, application_url=excluded.application_url,
  source=excluded.source, verified=excluded.verified;

insert into public.mentors
  (id,name,headline,location,about,journey,journey_tags,relevant_goals,experience,skills,can_help_with,willing_to_help_with,languages,availability,verified,experience_level) values
  ('woman-001','Aditi Sharma','ML Engineer at a global technology company','Bengaluru, India','Studied AI abroad on a full scholarship and now works on applied ML systems. Enjoys helping students navigate research-heavy applications.',array['Engineering student','Research assistant','Master''s abroad','ML Engineer']::text[],array['Study Abroad','Research','Women in Tech','Higher Education']::text[],array['Study abroad','Get a scholarship','Build my skills']::text[],array['AI & Technology','Research']::text[],array['Machine Learning','Python','Research','Interview Preparation']::text[],array['Study abroad applications','AI career guidance','Research opportunities','Graduate school applications']::text[],array['Mentorship','Application review','Study abroad guidance','Career advice']::text[],array['English','Hindi']::text[],'Occasional',true,'Experienced'),
  ('woman-002','Rhea Kapoor','Founder & CEO, early-stage fintech startup','Mumbai, India','Left a finance career to start her own company. Has raised two funding rounds and enjoys demystifying fundraising for first-time founders.',array['Investment analyst','MBA','Founder']::text[],array['Entrepreneurship','Funding','Career Change','Leadership']::text[],array['Start a business','Find funding','Change careers']::text[],array['Business','Finance','Entrepreneurship']::text[],array['Finance','Leadership','Public Speaking']::text[],array['Fundraising strategy','Pitch deck review','Early hiring','Founder mindset']::text[],array['Mentorship','Career advice','Entrepreneurship']::text[],array['English','Hindi']::text[],'Rare',true,'Experienced'),
  ('woman-003','Meera Iyer','Senior Product Designer at a design studio','Remote','Moved from graphic design into product design mid-career. Passionate about helping career changers build a design portfolio.',array['Graphic designer','UX bootcamp','Product Designer','Senior Product Designer']::text[],array['Career Change','First Job','Freelancing']::text[],array['Change careers','Build my skills','Get my first job']::text[],array['Design']::text[],array['UI/UX','Communication','Leadership']::text[],array['Portfolio reviews','Design career transitions','Freelance-to-full-time moves']::text[],array['Portfolio feedback','Career advice','Mentorship']::text[],array['English']::text[],'Frequent',true,'Experienced'),
  ('woman-004','Dr. Kavya Reddy','Postdoctoral researcher in computational biology','International','Completed her PhD abroad and now researches computational approaches to healthcare. Enjoys mentoring students applying to graduate programs.',array['Undergraduate research','PhD abroad','Postdoctoral researcher']::text[],array['Study Abroad','Research','Higher Education']::text[],array['Study abroad','Get a scholarship','Build my skills']::text[],array['Research','Healthcare']::text[],array['Research','Writing','Public Speaking']::text[],array['PhD applications','Research proposals','Academic funding']::text[],array['Application review','Study abroad guidance','Career advice']::text[],array['English']::text[],'Occasional',true,'Experienced'),
  ('woman-005','Sana Iqbal','Corporate lawyer turned legal-tech founder','Delhi, India','Practiced corporate law for six years before starting a legal-tech company. Helps women considering non-traditional legal careers.',array['Law school','Corporate lawyer','Legal-tech founder']::text[],array['Career Change','Entrepreneurship','Leadership']::text[],array['Change careers','Start a business','Grow my network']::text[],array['Law','Entrepreneurship']::text[],array['Leadership','Communication','Writing']::text[],array['Legal career paths','Transitioning out of law','Early-stage legal strategy']::text[],array['Career advice','Mentorship','Entrepreneurship']::text[],array['English','Hindi']::text[],'Rare',true,'Experienced'),
  ('woman-006','Priya Nambiar','VP of Finance at a mid-size manufacturing company','Chennai, India','Two decades in corporate finance, including a return to work after a career break. Enjoys helping women navigate return-to-work transitions.',array['Finance analyst','Career break','Returnship','VP of Finance']::text[],array['Career Return','Leadership']::text[],array['Return to work','Grow my network']::text[],array['Finance','Leadership']::text[],array['Finance','Leadership','Communication']::text[],array['Returning after a career break','Finance career growth','Negotiating a return offer']::text[],array['Career advice','Mentorship']::text[],array['English','Tamil']::text[],'Occasional',true,'Experienced'),
  ('woman-007','Neha Bhatt','Growth Marketing Lead at a consumer tech company','Remote','Built her marketing career across three industries. Enjoys helping early-career marketers figure out their specialization.',array['Marketing intern','Brand associate','Growth Marketing Lead']::text[],array['First Job','Women in Tech']::text[],array['Get my first job','Find an internship','Build my skills']::text[],array['Marketing','Business']::text[],array['Marketing','Communication','Writing']::text[],array['Choosing a marketing specialization','Landing a first marketing role','Portfolio/case studies']::text[],array['Career advice','Interview preparation','Networking']::text[],array['English','Hindi']::text[],'Frequent',true,'Mid-level'),
  ('woman-008','Ritu Malhotra','Engineering Director, Women in Tech community organizer','Bengaluru, India','Leads a 40-person engineering org and organizes a regional Women in Tech meetup. Focused on building the next generation of technical leaders.',array['Software engineer','Engineering manager','Engineering Director']::text[],array['Women in Tech','Leadership']::text[],array['Grow my network','Change careers','Build my skills']::text[],array['AI & Technology','Leadership']::text[],array['Leadership','Communication','Python']::text[],array['Moving into engineering leadership','Navigating being the only woman in the room','Technical career growth']::text[],array['Mentorship','Career advice','Networking']::text[],array['English','Hindi']::text[],'Occasional',true,'Experienced'),
  ('woman-009','Farida Khan','Founder of a social enterprise supporting rural education','International','Started a nonprofit-turned-social-enterprise after a career in consulting. Passionate about mission-driven entrepreneurship.',array['Management consultant','Fellowship abroad','Social enterprise founder']::text[],array['Entrepreneurship','Study Abroad','Funding']::text[],array['Start a business','Find funding','Study abroad']::text[],array['Business','Entrepreneurship']::text[],array['Leadership','Writing','Research']::text[],array['Social enterprise fundraising','Fellowship applications','Mission-driven career pivots']::text[],array['Mentorship','Entrepreneurship','Study abroad guidance']::text[],array['English']::text[],'Rare',true,'Experienced'),
  ('woman-010','Ananya Joshi','Master''s student in AI at a university abroad','International','Currently in the middle of her AI master''s abroad, having gone through the scholarship process just last year. Loves helping applicants who are where she recently was.',array['Engineering student','Scholarship applicant','Master''s student abroad']::text[],array['Study Abroad','Higher Education','First Job']::text[],array['Study abroad','Get a scholarship']::text[],array['AI & Technology','Research']::text[],array['AI/ML','Data Science','Research']::text[],array['Recent scholarship application experience','Choosing programs','Statement of purpose review']::text[],array['Application review','Study abroad guidance','Networking']::text[],array['English','Hindi']::text[],'Frequent',true,'Early career'),
  ('woman-011','Ishita Verma','Startup founder building a D2C skincare brand','Mumbai, India','Bootstrapped her company from a college side-project. Enjoys helping first-time founders with the early, scrappy stage.',array['Marketing intern','Side-project founder','Full-time founder']::text[],array['Entrepreneurship','First Job']::text[],array['Start a business','Find funding']::text[],array['Entrepreneurship','Marketing','Business']::text[],array['Marketing','Leadership','Finance']::text[],array['Bootstrapping a brand','Early customer acquisition','Balancing a day job and a startup']::text[],array['Entrepreneurship','Career advice','Networking']::text[],array['English','Hindi']::text[],'Occasional',true,'Mid-level'),
  ('woman-012','Sophia Chen','Data Scientist at a healthcare analytics company','Remote','Transitioned from academic research into industry data science. Enjoys helping researchers figure out an industry path.',array['PhD candidate','Research-to-industry transition','Data Scientist']::text[],array['Career Change','Research','Interview Preparation']::text[],array['Change careers','Build my skills','Get my first job']::text[],array['AI & Technology','Research','Healthcare']::text[],array['Data Science','Python','AI/ML']::text[],array['Academia-to-industry transitions','Data science interview prep','Resume translation from research']::text[],array['Interview preparation','Career advice','Mentorship']::text[],array['English','Mandarin']::text[],'Frequent',true,'Mid-level'),
  ('woman-013','Divya Nair','UX Researcher at a large e-commerce company','Bengaluru, India','Started in customer support and worked her way into UX research. Enjoys helping people break into research roles without a traditional background.',array['Customer support','Research assistant','UX Researcher']::text[],array['Career Change','First Job','Interview Preparation']::text[],array['Change careers','Get my first job','Build my skills']::text[],array['Design','Research']::text[],array['Research','Communication','UI/UX']::text[],array['Breaking into UX research','Portfolio case studies','Non-traditional career paths']::text[],array['Career advice','Portfolio feedback','Interview preparation']::text[],array['English']::text[],'Occasional',true,'Mid-level'),
  ('woman-014','Dr. Lakshmi Menon','General physician, now health-tech advisor','Kochi, India','Practiced medicine for a decade before advising health-tech startups part-time. Interested in helping clinicians explore adjacent career paths.',array['Medical school','General physician','Health-tech advisor']::text[],array['Career Change','Leadership']::text[],array['Change careers','Grow my network']::text[],array['Healthcare','Business']::text[],array['Communication','Leadership','Research']::text[],array['Clinician career pivots','Health-tech industry basics','Balancing practice and advisory work']::text[],array['Career advice','Mentorship']::text[],array['English','Hindi']::text[],'Rare',true,'Experienced'),
  ('woman-015','Zara Ahmed','Freelance brand strategist, formerly agency-side','Remote','Left agency life to freelance full-time. Enjoys helping people evaluate whether freelancing is right for them.',array['Junior strategist','Agency lead','Freelance strategist']::text[],array['Freelancing','Career Change']::text[],array['Change careers','Grow my network','Build my skills']::text[],array['Marketing','Business']::text[],array['Marketing','Communication','Writing']::text[],array['Going freelance','Pricing and client management','Building a personal brand']::text[],array['Career advice','Networking','Entrepreneurship']::text[],array['English']::text[],'Frequent',true,'Mid-level')
on conflict (id) do update set
  name=excluded.name, headline=excluded.headline, location=excluded.location, about=excluded.about,
  journey=excluded.journey, journey_tags=excluded.journey_tags, relevant_goals=excluded.relevant_goals,
  experience=excluded.experience, skills=excluded.skills, can_help_with=excluded.can_help_with,
  willing_to_help_with=excluded.willing_to_help_with, languages=excluded.languages,
  availability=excluded.availability, verified=excluded.verified, experience_level=excluded.experience_level;
