-- ============================================================================
-- ⚠️  DEMO / DEVELOPMENT DATA ONLY — DO NOT RUN THIS IN PRODUCTION.
-- ----------------------------------------------------------------------------
-- Every opportunity row below is fabricated sample data: fake organizations,
-- a fake application_url ("#"), and source = "Demo". It exists only so a
-- fresh local install has something to click through before you've added
-- real opportunities.
--
-- Run this ONLY in a local/dev Supabase project, never against production.
-- In production, leave the `opportunities` table empty after schema.sql +
-- 002_opportunity_engine.sql and add real listings via:
--   - the admin dashboard (/admin/opportunities), or
--   - a verified organization's own dashboard (/org/dashboard), or
--   - the ingestion pipeline (see supabase/functions/ingest-opportunities)
-- See README.md → "Opportunity Engine" for the full explanation.
-- ============================================================================
-- AUTO-GENERATED seed data for NEXA. Run AFTER schema.sql.
-- Idempotent: re-running upserts the same catalog rows.

insert into public.opportunities
  (id,title,organization,type,description,location,remote,categories,goals,career_stages,skills,funding,deadline,eligibility,benefits,application_url,source,verified) values
  ('ai-research-fellowship','AI Research Fellowship','Demo Research Foundation','Fellowship','A funded fellowship for early-career researchers working on applied AI/ML problems, with placement at partner labs abroad.','International',false,array['AI & Technology','Research']::text[],array['Study abroad','Get a scholarship','Build my skills']::text[],array['Student','Early career']::text[],array['AI/ML','Python','Research']::text[],'{"type":"Fully funded","amount":"Tuition + stipend"}'::jsonb,'2026-09-14'::date,array['Enrolled in or recently graduated from a STEM program','Demonstrated research interest in AI/ML','Open to international relocation']::text[],array['Full tuition and stipend','Mentorship from senior researchers','Publication support']::text[],'#','Demo',true),
  ('women-in-ai-scholarship','Women in AI Scholarship','Global AI Trust','Scholarship','Scholarship supporting women pursuing graduate study in artificial intelligence or machine learning.','International',false,array['AI & Technology','Women in Tech']::text[],array['Get a scholarship','Study abroad']::text[],array['Student']::text[],array['AI/ML','Data Science']::text[],'{"type":"Fully funded","amount":"Full tuition"}'::jsonb,'2026-09-21'::date,array['Identifies as a woman','Admitted to or enrolled in a graduate AI/ML program','Strong academic record']::text[],array['Full tuition coverage','Community of past scholars','Annual summit invitation']::text[],'#','Demo',true),
  ('global-research-fellowship','Global Research Fellowship','Meridian Foundation','Fellowship','Funding and placement for early-stage researchers across social science, health, and technology fields.','International',false,array['Research','Social Impact']::text[],array['Find funding','Study abroad']::text[],array['Student','Career changer']::text[],array['Research','Writing']::text[],'{"type":"Fully funded","amount":"$18,000 + travel"}'::jsonb,'2026-09-30'::date,array['Bachelor''s degree or equivalent experience','Research proposal required','No age restriction']::text[],array['Full funding','Institutional affiliation','Publication mentorship']::text[],'#','Demo',true),
  ('future-leaders-program','Future Leaders Program','Confluence Institute','Leadership','A year-long leadership development program for professionals moving into senior roles.','Remote',true,array['Leadership','Business']::text[],array['Grow my network','Change careers']::text[],array['Working professional','Career changer']::text[],array['Leadership','Communication']::text[],'{"type":"Paid","amount":"Stipend on completion"}'::jsonb,'2026-10-05'::date,array['3+ years of professional experience','Manager-track or aspiring to be','Available for monthly virtual sessions']::text[],array['1:1 executive coaching','Peer cohort','Certificate of completion']::text[],'#','Demo',true),
  ('tech-returnship','Tech Returnship Program','NorthPeak Systems','Returnship','A structured 16-week paid returnship for professionals re-entering the tech workforce after a career break.','Remote',true,array['AI & Technology','Business']::text[],array['Return to work','Build my skills']::text[],array['Returning to work']::text[],array['JavaScript','Communication']::text[],'{"type":"Paid","amount":"Market-rate salary"}'::jsonb,'2026-10-20'::date,array['Career break of 1+ years','Prior professional experience in tech or adjacent field','Based in or willing to work remote hours overlapping IST']::text[],array['Paid 16-week program','Mentorship','Potential full-time conversion']::text[],'#','Demo',true),
  ('women-founders-grant','Women Founders Micro-Grant','Catalyst Collective','Grant','Non-dilutive micro-grants for early-stage founders building their first company.','International',true,array['Entrepreneurship','Finance','Women in Tech']::text[],array['Start a business','Find funding']::text[],array['Entrepreneur']::text[],array['Finance','Leadership']::text[],'{"type":"Fully funded","amount":"$5,000 grant"}'::jsonb,'2026-11-12'::date,array['Founding team is majority women-led','Company under 2 years old','Not yet raised institutional funding']::text[],array['$5,000 non-dilutive grant','Founder community access','Office hours with mentors']::text[],'#','Demo',true),
  ('design-product-internship','Design & Product Bridge Internship','Studio Norr','Internship','A 10-week paid internship pairing design and product thinking, for early-career candidates building a portfolio.','Remote',true,array['Design & Creativity','Business']::text[],array['Find an internship','Build my skills']::text[],array['Student','Early career']::text[],array['UI/UX','Communication']::text[],'{"type":"Paid","amount":"$1,800/month"}'::jsonb,'2026-12-01'::date,array['Portfolio of design work (student or personal projects accepted)','Available for 10 consecutive weeks','No prior professional experience required']::text[],array['Paid stipend','Portfolio review','Mentor pairing']::text[],'#','Demo',true),
  ('healthtech-accelerator','HealthTech Founders Accelerator','Ridgeline Ventures','Incubator','12-week accelerator for early-stage health technology startups, with a small equity investment.','International',false,array['Healthcare','Entrepreneurship']::text[],array['Start a business','Grow my network']::text[],array['Entrepreneur']::text[],array['Research','Leadership']::text[],'{"type":"Partially funded","amount":"$25,000 for 5% equity"}'::jsonb,'2026-09-05'::date,array['Working prototype or MVP','Founding team of 1-4 people','Health/medtech focus']::text[],array['Seed investment','Clinical advisor network','Demo day']::text[],'#','Demo',true),
  ('public-policy-fellowship','Public Policy Fellowship','Anthemis Policy Lab','Fellowship','A 6-month fellowship for people transitioning into public policy and social impact careers.','Remote',true,array['Social Impact','Law']::text[],array['Change careers','Build my skills']::text[],array['Career changer','Between opportunities']::text[],array['Research','Writing','Public Speaking']::text[],'{"type":"Paid","amount":"$2,200/month"}'::jsonb,'2026-08-25'::date,array['Bachelor''s degree in any field','Interest in public policy or governance','Strong written communication']::text[],array['Paid stipend','Policy-writing workshops','Alumni network']::text[],'#','Demo',true),
  ('stem-mentorship-circle','STEM Mentorship Circle','Global STEM Network','Mentorship','A structured 4-month mentorship program pairing women in STEM with senior mentors in their field.','Remote',true,array['AI & Technology','Research','Women in Tech']::text[],array['Find mentors','Grow my network']::text[],array['Student','Early career','Career changer']::text[],array['Communication','Leadership']::text[],'{"type":"No funding","amount":null}'::jsonb,'2026-09-10'::date,array['Identifies as a woman in a STEM field','Available for monthly 1:1 sessions','No cost to apply']::text[],array['1:1 mentorship','Peer cohort events','Career workshops']::text[],'#','Demo',true),
  ('founders-pitch-competition','Emerging Founders Pitch Competition','Catalyst Collective','Competition','A pitch competition for early-stage founders with cash prizes and investor introductions.','International',false,array['Entrepreneurship','Business']::text[],array['Start a business','Find funding']::text[],array['Entrepreneur','Working professional']::text[],array['Public Speaking','Finance']::text[],'{"type":"Fully funded","amount":"$10,000 top prize"}'::jsonb,'2026-10-30'::date,array['Company under 3 years old','Under $500K raised to date','10-minute pitch deck required']::text[],array['Cash prizes','Investor introductions','Media coverage']::text[],'#','Demo',true),
  ('early-career-data-fellowship','Early-Career Data Science Fellowship','Meridian Foundation','Fellowship','A paid fellowship placing early-career candidates in data science roles at partner nonprofits.','Remote',true,array['AI & Technology','Social Impact']::text[],array['Get my first job','Build my skills']::text[],array['Student','Early career']::text[],array['Python','Data Science']::text[],'{"type":"Paid","amount":"$3,000/month"}'::jsonb,'2026-09-18'::date,array['Coursework or self-study in data science','Portfolio project preferred','Available full-time for 6 months']::text[],array['Paid placement','Nonprofit partner network','Skills certification']::text[],'#','Demo',true),
  ('creative-leadership-grant','Creative Leadership Grant','Studio Norr','Grant','Grant funding for designers and creatives moving into creative-direction and leadership roles.','Remote',true,array['Design & Creativity','Leadership']::text[],array['Grow my network','Build my skills']::text[],array['Working professional']::text[],array['UI/UX','Leadership']::text[],'{"type":"Partially funded","amount":"$4,000"}'::jsonb,'2026-11-25'::date,array['3+ years in a design discipline','Portfolio required','Based anywhere, remote-friendly']::text[],array['Grant funding','Leadership coaching','Studio community access']::text[],'#','Demo',true),
  ('return-to-finance-program','Return to Finance Program','NorthPeak Systems','Returnship','A returnship for finance professionals re-entering the workforce, with flexible part-time options.','India',false,array['Finance','Business']::text[],array['Return to work','Grow my network']::text[],array['Returning to work']::text[],array['Finance','Communication']::text[],'{"type":"Paid","amount":"Market-rate, pro-rated"}'::jsonb,'2026-12-15'::date,array['Career break of 1+ years','Prior finance or accounting experience','Based in India, hybrid role']::text[],array['Flexible hours','Paid role','Return-to-work coaching']::text[],'#','Demo',true),
  ('education-innovation-fellowship','Education Innovation Fellowship','Anthemis Policy Lab','Fellowship','A fellowship for educators and technologists building new approaches to learning.','International',false,array['Education','Social Impact']::text[],array['Change careers','Grow my network']::text[],array['Career changer','Working professional']::text[],array['Research','Communication']::text[],'{"type":"Fully funded","amount":"Stipend + travel"}'::jsonb,'2027-01-15'::date,array['Experience in education, ed-tech, or related field','Proposal required','Open to relocation for the fellowship term']::text[],array['Full funding','Global cohort','Publication opportunity']::text[],'#','Demo',true),
  ('media-storytelling-lab','Media & Storytelling Lab','Global STEM Network','Incubator','An 8-week lab for early-career media makers developing an independent storytelling project.','Remote',true,array['Media','Design & Creativity']::text[],array['Build my skills','Find an internship']::text[],array['Student','Early career']::text[],array['Writing','Communication']::text[],'{"type":"Unpaid","amount":null}'::jsonb,'2027-02-10'::date,array['A project concept or draft required','No professional experience required','Available for weekly virtual workshops']::text[],array['Mentor feedback','Peer showcase','Distribution support']::text[],'#','Demo',true),
  ('law-access-scholarship','Access to Law Scholarship','Anthemis Policy Lab','Scholarship','A scholarship supporting first-generation students pursuing legal education.','International',false,array['Law','Social Impact']::text[],array['Get a scholarship','Change careers']::text[],array['Student','Career changer']::text[],array['Research','Writing']::text[],'{"type":"Fully funded","amount":"Full tuition"}'::jsonb,'2026-08-18'::date,array['First-generation college student','Admitted to an accredited law program','Financial need demonstrated']::text[],array['Full tuition','Bar exam prep stipend','Mentor network']::text[],'#','Demo',true),
  ('archived-summer-fellowship','Summer Research Fellowship (Closed)','Demo Research Foundation','Fellowship','A past cohort''s summer fellowship — kept visible as a closed listing so deadline states are testable end to end.','International',false,array['Research','AI & Technology']::text[],array['Study abroad','Build my skills']::text[],array['Student']::text[],array['Research']::text[],'{"type":"Fully funded","amount":"Stipend"}'::jsonb,'2026-07-01'::date,array['This cohort has closed']::text[],array['N/A — applications closed']::text[],'#','Demo',true)
on conflict (id) do update set
  title=excluded.title, organization=excluded.organization, type=excluded.type, description=excluded.description,
  location=excluded.location, remote=excluded.remote, categories=excluded.categories, goals=excluded.goals,
  career_stages=excluded.career_stages, skills=excluded.skills, funding=excluded.funding, deadline=excluded.deadline,
  eligibility=excluded.eligibility, benefits=excluded.benefits, application_url=excluded.application_url,
  source=excluded.source, verified=excluded.verified;

-- Mentors are intentionally NOT seeded here, ever. A mentor row can only
-- come from a real person filling out "Become a Mentor" themselves (see
-- migrations/003_mentor_network.sql) -- there is no such thing as sample
-- mentor data. The 15 fabricated profiles that used to live in this file
-- (fake names, fake bios, fake photos) were removed for exactly that reason.
-- Every row below is a REAL organization at the URL given, individually
-- verified by web search as of Aug 2026 (see migrations/011_real_verified_communities.sql
-- for the same fix applied directly to already-deployed databases).
insert into public.communities
  (id,name,category,why,url,interests,priorities) values
  ('c1','Women in AI','Technology','Global nonprofit community for women working in or studying AI.','https://www.womeninai.co/','{"AI & Technology"}','{"Women-focused opportunities"}'),
  ('c2','Women Founders Network','Entrepreneurship','Nonprofit providing education, coaching, and funding access for women founders.','https://www.womenfoundersnetwork.org/','{"Entrepreneurship","Business"}','{"Women-focused opportunities","Networking"}'),
  ('c3','Association for Women in Science','Research','National advocacy organization and peer network for women across every STEM discipline.','https://awis.org/','{"Research","AI & Technology"}','{"Networking"}'),
  ('c4','Chief','Career growth','Private membership network and executive coaching community for senior women leaders.','https://chief.com/','{"Leadership"}','{"Career growth","Women-focused opportunities"}'),
  ('c5','Ladies, Wine & Design','Design & Creativity','Global chapter-based nonprofit offering mentorship and portfolio reviews for women in creative fields.','https://ladieswinedesign.com/','{"Design & Creativity"}','{"Networking","Women-focused opportunities"}'),
  ('c6','Financial Women''s Association','Finance','Professional association since 1956 for women in banking, investing, and fintech.','https://www.fwa.org/','{"Finance"}','{"Career growth","Women-focused opportunities"}'),
  ('c7','American Medical Women''s Association','Healthcare','The oldest multispecialty organization advancing women physicians and medical students.','https://amwa-doc.org/','{"Healthcare"}','{"Mentorship","Women-focused opportunities"}'),
  ('c8','National Association of Women Lawyers','Law','National organization advancing women in the legal profession since 1899.','https://www.nawl.org/','{"Law"}','{"Mentorship","Women-focused opportunities"}'),
  ('c9','EdTech Women','Education','Educators and founders building the future of learning, with chapters in multiple cities.','https://www.edtechwomen.com/','{"Education"}','{"Networking","Women-focused opportunities"}'),
  ('c10','Alliance for Women in Media','Media','The longest-established professional association advancing women across broadcasting and media.','https://allwomeninmedia.org/','{"Media"}','{"Networking","Women-focused opportunities"}'),
  ('c11','Vital Voices','Social Impact','Global network investing in women leaders driving human rights and economic change.','https://www.vitalvoices.org/','{"Social Impact"}','{"Mentorship","Networking"}'),
  ('c12','Ellevate Network','Career growth','Global professional women''s network with peer mentoring and local chapters, from early career to executive.','https://ellevatenetwork.com/','{"Business","Leadership"}','{"Mentorship","Career growth"}')
on conflict (id) do update set
  name=excluded.name, category=excluded.category, why=excluded.why, url=excluded.url,
  interests=excluded.interests, priorities=excluded.priorities;